config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :new, :update, :destroy, :create, :show] do 
    resources :guesses, only: [:create]
  end

  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  MAX_LIVES = 9

  has_many :guesses, dependent: :delete_all
  validates_associated :guesses

  def self.load_secret_words
    File.open('db/words.txt').map { |word| word.strip }
  end

  # def load_secret_words
  #   File.open('db/words.txt').map { |word| word.strip }
  # end

  def remaining_lives
    MAX_LIVES - guesses.where.not(value: secret_word.chars).count
  end

  def letters_guessed
    guesses.pluck(:value)
  end

  def correct_guess
    guesses.where(value: secret_word.chars).pluck(:value).uniq.count
  end

  def formatted_updated_at
    updated_at.strftime("%Y/%m/%d - %H:%M")
  end

  def check_dupe?(letter)
    letters_guessed.include?(letter)
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game

  validates :value, format: { with: /\A[A-Z]{1}+\Z/, message: 'Only allows single letters between A and Z' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show

  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games or /games.json
  def create
    game_builder = GameBuilder.new(game_params)
    @game = game_builder.call

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_path(@game), notice: "Game was successfully created." }
        # format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:player_name)
    end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create    
    game = Game.find(params[:game_id])
    guess_service = GuessService.new(game, guess_params)
    
    flash[:notice] = guess_service.call
    redirect_to game
 
  rescue ActiveRecord::RecordInvalid
    redirect_to game, alert: "Unable to create guesses."
   
  end

  private

    def guess_params
      params.require(:guess).permit(:value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :player_name, style: "display: block" %>
    <%= form.text_field :player_name %>
  </div>

  <div>
    <%= form.label :game_result, style: "display: block" %>
    <%= form.text_field :game_result %>
  </div>

  <div>
    <%= form.label :secret_word, style: "display: block" %>
    <%= form.text_field :secret_word %>
  </div>

  <div>
    <%= form.label :remaining_lives, style: "display: block" %>
    <%= form.number_field :remaining_lives %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Player name:</strong>
    <%= game.player_name %>
  </p>

  <p>
    <strong>Game result:</strong>
    <%= game.game_result %>
  </p>

  <p>
    <strong>Secret word:</strong>
    <%= game.secret_word %>
  </p>

  <p>
    <strong>Remaining lives:</strong>
    <%= game.remaining_lives %>
  </p>

</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <table class="game-list">
    <tbody>
      <tr>
        <th>Player name</th>
        <th>Last time played</th>
        <th>Progress</th>
      <tr>

      <% @games.each do |game| %>
      <tr>
        <td>
          <%= link_to game.player_name, game %>
        </td>
        <td>
          <%= game.formatted_updated_at %>
        </td>
        <td>
        <%= game.game_result %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br />
<br />

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= form_for(@game) do |post_form| %>
  <% if @game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% @game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= post_form.label :player_name %>
  <%= post_form.text_field :player_name %>
  <br />
  <%= post_form.submit %>
<% end %>

<br />
<br />

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<% key_input = [
    "QWERTYUIOP",
    "ASDFGHJKL",
    "ZXCVBNM"
  ]
%>

<p style="color: green"><%= notice %></p>

<div>Player name: <%= @game.player_name %></div>
<div>Remaining lives: <%= @game.remaining_lives %></div>
<br>

<% @game.secret_word.chars.map do | letter | %>
  <% if @game.letters_guessed.include?(letter) %>
    <span><%= letter %></span>
  <% elsif %>
    <span>@</span>
  <% end %>
<% end %>

<br>
<br>

<% key_input.each do | row | %>
  <div class="input_row">
    <% row.split('') do | letter | %>
      <%= button_to letter, game_guesses_path(@game), params: { guess: { value: letter.upcase } }, disabled: @game.check_dupe?(letter) %>
      <%# <%= button_to letter, game_guesses_path(@game), params: {'guess[value]' => letter.upcase } %>
    <% end %>
  </div>
  <br />
<% end %>

<br>
<br>
<%= @game.game_result %>

<br>
<br>
<% if @game.game_result == 'Lose' %>
  <span>Your secret word is: <em><%= @game.secret_word %></em></span>
<% end %>

<br>
<br>

<div>
  <%= link_to "Back to games", games_path %>
  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevtrainRubyRailsHangman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>